// <auto-generated />
using System;
using EMS.Domain.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EMS.Domain.Database.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260321091812_AddOrganizationDirectory")]
partial class AddOrganizationDirectory
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("EMS.Domain.DbModels.Department", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Code")
                    .HasMaxLength(32)
                    .HasColumnType("nvarchar(32)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int>("OrganizationId")
                    .HasColumnType("int");

                b.Property<int?>("ParentDepartmentId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("OrganizationId");

                b.HasIndex("ParentDepartmentId");

                b.ToTable("Departments", "org");
            });

        modelBuilder.Entity("EMS.Domain.DbModels.Employee", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<DateTime>("CreatedAtUtc")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.Property<DateTime>("DateJoined")
                    .HasColumnType("datetime2");

                b.Property<DateTime>("DateOfBirth")
                    .HasColumnType("datetime2");

                b.Property<int?>("DepartmentId")
                    .HasColumnType("int");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("EmployeeNumber")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("nvarchar(32)");

                b.Property<int>("EmploymentStatus")
                    .HasColumnType("int");

                b.Property<string>("ExternalIdentityKey")
                    .HasMaxLength(450)
                    .HasColumnType("nvarchar(450)");

                b.Property<string>("FirstName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("JobTitle")
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<string>("LastName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<int?>("LocationId")
                    .HasColumnType("int");

                b.Property<int?>("ManagerId")
                    .HasColumnType("int");

                b.Property<int>("OrganizationId")
                    .HasColumnType("int");

                b.Property<string>("PhoneNumber")
                    .HasMaxLength(32)
                    .HasColumnType("nvarchar(32)");

                b.Property<DateTime>("UpdatedAtUtc")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("datetime2")
                    .HasDefaultValueSql("GETUTCDATE()");

                b.HasKey("Id");

                b.HasIndex("DepartmentId");

                b.HasIndex("LocationId");

                b.HasIndex("ManagerId");

                b.HasIndex("OrganizationId", "Email")
                    .IsUnique();

                b.HasIndex("OrganizationId", "EmployeeNumber")
                    .IsUnique();

                b.ToTable("Employees", "org");
            });

        modelBuilder.Entity("EMS.Domain.DbModels.Location", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("City")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("Country")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Line1")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Line2")
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int>("OrganizationId")
                    .HasColumnType("int");

                b.Property<string>("PostalCode")
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("Region")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.HasKey("Id");

                b.HasIndex("OrganizationId");

                b.ToTable("Locations", "org");
            });

        modelBuilder.Entity("EMS.Domain.DbModels.Organization", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Code")
                    .HasMaxLength(32)
                    .HasColumnType("nvarchar(32)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique()
                    .HasFilter("[Code] IS NOT NULL");

                b.ToTable("Organizations", "org");
            });

        modelBuilder.Entity("EMS.Domain.DbModels.Department", b =>
            {
                b.HasOne("EMS.Domain.DbModels.Organization", "Organization")
                    .WithMany()
                    .HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("EMS.Domain.DbModels.Department", "ParentDepartment")
                    .WithMany("SubDepartments")
                    .HasForeignKey("ParentDepartmentId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Organization");

                b.Navigation("ParentDepartment");
            });

        modelBuilder.Entity("EMS.Domain.DbModels.Employee", b =>
            {
                b.HasOne("EMS.Domain.DbModels.Department", "Department")
                    .WithMany()
                    .HasForeignKey("DepartmentId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("EMS.Domain.DbModels.Location", "Location")
                    .WithMany()
                    .HasForeignKey("LocationId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.HasOne("EMS.Domain.DbModels.Employee", "Manager")
                    .WithMany("DirectReports")
                    .HasForeignKey("ManagerId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("EMS.Domain.DbModels.Organization", "Organization")
                    .WithMany()
                    .HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Department");

                b.Navigation("Location");

                b.Navigation("Manager");

                b.Navigation("Organization");
            });

        modelBuilder.Entity("EMS.Domain.DbModels.Location", b =>
            {
                b.HasOne("EMS.Domain.DbModels.Organization", "Organization")
                    .WithMany()
                    .HasForeignKey("OrganizationId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Organization");
            });

        modelBuilder.Entity("EMS.Domain.DbModels.Department", b =>
            {
                b.Navigation("SubDepartments");
            });

        modelBuilder.Entity("EMS.Domain.DbModels.Employee", b =>
            {
                b.Navigation("DirectReports");
            });
#pragma warning restore 612, 618
    }
}
